### ISSUE TITLE
Questions on selling TBS Source Two / One in Mexico

### ISSUE THREAD

**Issue by memo2087** [ps915/source_two#2]
Hi, I am located in Guadalajara, Mexico, and am interested in distributing or producing TBS Source One and Two Kits for selling in Mexico and Latin America, I would like to know what are the restrictions on doing this, and if there is a wholesale manufacturer of these kits that you recommend to start working with.  I have more questions on it, but would like to get in touch with someone that could help me with a direct phone call or something more agile.

**Comment by ps915** [comment]
Hi Memo2087,

i recommend Teamblacksheep as your distributor of both frames when you don't want to produce them yourself. I am not allowed to share the direct e-mail address of the TBS Dealersupport but you can reach them by just creating a ticket here: https://team-blacksheep.freshdesk.com/support/tickets/new

If you want to cut it yourself, it's perfectly fine. You can download all files and send it to a manufacturer. Please read our license how to name the frame in your shop and your are ready to go! =)

Hope that helps,
Phil
